
export const DARK_MODE = 'DARK_MODE'
export const OPEN_MODAL = 'OPEN_MODAL'
export const MENU_SELECTED = 'MENU_SELECTED'
export const REALISATION_SELECTED = 'REALISATION_SELECTED'
export const RESET_REALISATION_SELECTED = 'RESET_REALISATION_SELECTED'
